[project]
name = "generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "faker>=37.12.0",
    "pandas>=2.3.3",
    "pyodbc>=5.3.0",
    "sqlalchemy>=2.0.44",
]
